Specflow actions windows app driver
SpecFlowOSS/SpecFlow.Actions pull request #33
Opened 2021-09-29 09:01 UTC by JordanWestern

2021-09-29 11:25 UTC, SabotageAndi requested changes

2021-09-29 11:25 UTC, SabotageAndi commented on Plugins/SpecFlow.Actions.Configuration/SpecFlow.Actions.Configuration/SpecFlow.Actions.Configuration.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.4.240" />
This package is added via `Directory.Build.props` (https://github.com/SpecFlowOSS/SpecFlow.Actions/blob/main/Plugins/Directory.Build.props#L13). Please update there the version number

2021-09-29 11:25 UTC, SabotageAndi commented on Plugins/SpecFlow.Actions.WindowsAppDriver/SpecFlow.Actions.WindowsAppDriver/SpecFlow.Actions.WindowsAppDriver.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.4.240" />
some here

2021-09-29 11:25 UTC, SabotageAndi commented on Plugins/SpecFlow.Actions.WindowsAppDriver/Example/Specflow.Actions.json
> +    "WindowsAppDriverPath": "{WINDOWS_APP_DRIVER_EXECUTABLE_PATH}"
Should this work? Do we have an environment variable expander for the configuration values? I didn't see any in the code.

2021-09-29 11:30 UTC, JordanWestern commented on Plugins/SpecFlow.Actions.WindowsAppDriver/Example/Specflow.Actions.json
> +    "WindowsAppDriverPath": "{WINDOWS_APP_DRIVER_EXECUTABLE_PATH}"
This is just a placeholder text has nothing to do with environment variables, its just to tell the user what is expected

2021-09-29 11:48 UTC, JordanWestern commented on Plugins/SpecFlow.Actions.Configuration/SpecFlow.Actions.Configuration/SpecFlow.Actions.Configuration.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.4.240" />
Did that by mistake, removed

2021-09-29 11:49 UTC, JordanWestern commented on Plugins/SpecFlow.Actions.WindowsAppDriver/SpecFlow.Actions.WindowsAppDriver/SpecFlow.Actions.WindowsAppDriver.csproj
> +    <PackageReference Update="Nerdbank.GitVersioning" Version="3.4.240" />
Did that by mistake, removed

2021-09-29 11:52 UTC, JordanWestern commented
@SabotageAndi  the build 'SpecFlow-Actions-WinAppDriver' was me figuring stuff out in AzDo, can be ignored as it has been removed

2021-10-04 11:20 UTC, SabotageAndi approved these changes

2021-10-05 10:03 UTC, merged